version: '3'

services:
  app:
    build: .
    tty: true
    stdin_open: true
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/mozi_pittan_game
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      POSTGRES_HOST_AUTH_METHOD: 'trust'

  db:
    image: postgres
    ports:
      - '5432:5432'
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_PASSWORD=password

volumes:
  postgresql-data:
    driver: local
