default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: db
  username: postgres
  password: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: mozi_pittan_game_development

test:
  <<: *default
  database: mozi_pittan_game_test
  host: <%= ENV['PGHOST'] || 'db' %>

production:
  <<: *default
  database: mozi_pittan_game_production
  username: mozi_pittan_game
  password: <%= ENV['MOZI_PITTAN_GAME_DATABASE_PASSWORD'] %>
